version: '3.9'

services:
    chat:
        build: chat
        volumes:
            - ./data:/var/data
        ports:
            - '8000:80'
    bot:
        build: bot
        ports:
            - '8001:80'
    redis:
        image: 'redis:alpine'
        restart: always
        hostname: redis
        # command: redis-server --requirepass admin
    # rabbitmq:
    #     image: rabbitmq:3-management-alpine
    #     restart: always
    #     container_name: 'rabbitmq'
    #     hostname: rabbitmq
    #     environment:
    #         RABBITMQ_DEFAULT_USER: 'admin'
    #         RABBITMQ_DEFAULT_PASS: 'admin'
    #     ports:
    #         - '5672:5672'
    #         - '15672:15672'
