version: '3.9'

services:
    chat:
        build: chat
        volumes:
            - ./data:/var/data
        ports:
            - '8000:80'
        depends_on:
            - "redis"
            - "rabbitmq"
    bot:
        build: bot
        depends_on:
            - "rabbitmq"
            - "botposter"
    botposter:
        build: botposter
        depends_on:
            - "rabbitmq"
    redis:
        image: 'redis:alpine'
        restart: always
        hostname: redis
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        container_name: 'rabbitmq'
        hostname: rabbitmq
        domainname: rabbitmq.io
        environment:
            RABBITMQ_DEFAULT_USER: 'admin'
            RABBITMQ_DEFAULT_PASS: 'admin'
        ports:
           - '5672:5672'
           - '15672:15672'
