print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
print('\n\n\n\t\tHELLO IM THE BOT!!!!!\n\n\n')
